### ISSUE TITLE
Can not connect to NFS share

### ISSUE THREAD

**Issue by theryno1984** [DustyArmstrong/xen-orchestra-arm#1] opened 2023-03-07 00:51 UTC
I can not figure out how to connect to an NFS share and successfully backup to it. I get the error "STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights." I am able to connect to the NFS share in this mode but when the backup finishes I get that error.

I added the flag "privileged: true" but then get the error : EACCES: permission denied, mkdir '/run/xo-server'. With this mode, I cant even connect to the NFS share.

I then added the correct directories with the correct permissions and get a new error : Command failed with exit code 1: mount -o domain=WORKGROUP -t cifs //192.168.50.103\All Backups/XCP-NG-VM-Backups /run/xo-server/mounts/70f849e6-10af-40e2-9ff3-7fcc868fb502
mount.cifs: permission denied: no match for /run/xo-server/mounts/70f849e6-10af-40e2-9ff3-7fcc868fb502 found in /etc/fstab

Not sure where to go from here to get the NFS share to connect and successfully backup to it. I had a version of Xen on an Ubuntu VM and it was able to connect to the NFS share so I know the credentials are correct. Any help here?

**Comment by DustyArmstrong** [comment] 2023-05-01 17:14
Hi there! It was quite a bodge to get this working at all, so there probably isn't a lot of help I can really offer. I have added my own remotes via SMB rather than NFS, which do work as intended. I would probably be inclined to try this repo instead https://github.com/Ezka77/xen-orchestra-ce as they have done a better job overall. From my own experience I think NFS issues are more of an XO thing itself rather than with the container, so I would definitely try SMB if you can work/live with that.

**Comment by DustyArmstrong** [comment] 2023-06-04 10:23
@theryno1984 just to follow up, did you get this sorted? Appreciate there's nothing I can really do to help, so I was going to close this issue but wanted to check with you before. Seems the issue is most likely related to privileges, NFS requires some elevated (root) abilities which I don't think are really catered for in this build unfortunately.

**Closed as completed** 2023-08-28 14:11 UTC
Labels: wontfix
